export const AUTH_SELECT_ROLE_PREFERENCE = 'AUTH_SELECT_ROLE_PREFERENCE';
export const CLEAR_REDUX_STATE = 'CLEAR_REDUX_STATE';
export const CA_LOGIN_BEGIN = 'CA_LOGIN_BEGIN';
export const CA_LOGIN_FAILURE = 'CA_LOGIN_FAILURE';
export const CA_LOGIN_DISMISS_ERROR = 'CA_LOGIN_DISMISS_ERROR';
export const CA_LOGIN_SUCCESS = 'CA_LOGIN_SUCCESS';
