export const CHECK_USER_EXISTENCE_BEGIN = 'CHECK_USER_EXISTENCE_BEGIN';
export const CHECK_USER_EXISTENCE_SUCCESS = 'CHECK_USER_EXISTENCE_SUCCESS';
export const CHECK_USER_EXISTENCE_FAILURE = 'CHECK_USER_EXISTENCE_FAILURE';
export const CHECK_USER_EXISTENCE_DISMISS_ERROR =
  'CHECK_USER_EXISTENCE_DISMISS_ERROR';
export const CREATE_NEW_CA_BEGIN = 'CREATE_NEW_CA_BEGIN';
export const CREATE_NEW_CA_SUCCESS = 'CREATE_NEW_CA_SUCCESS';
export const CREATE_NEW_CA_FAILURE = 'CREATE_NEW_CA_FAILURE';
export const CREATE_NEW_CA_DISMISS_ERROR = 'CREATE_NEW_CA_DISMISS_ERROR';
export const FETCH_TASK_LIST_BEGIN = 'FETCH_TASK_LIST_BEGIN';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAILURE = 'FETCH_TASK_LIST_FAILURE';
export const FETCH_TASK_LIST_DISMISS_ERROR = 'FETCH_TASK_LIST_DISMISS_ERROR';
export const FETCH_LEADERBOARD_BEGIN = 'FETCH_LEADERBOARD_BEGIN';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_FAILURE = 'FETCH_LEADERBOARD_FAILURE';
export const FETCH_LEADERBOARD_DISMISS_ERROR =
  'FETCH_LEADERBOARD_DISMISS_ERROR';
export const VIEW_TASK = 'VIEW_TASK';
export const SELECT_PHOTOS_BEGIN = 'SELECT_PHOTOS_BEGIN';
export const SELECT_PHOTOS_SUCCESS = 'SELECT_PHOTOS_SUCCESS';
export const SELECT_PHOTOS_FAILURE = 'SELECT_PHOTOS_FAILURE';
export const SELECT_PHOTOS_DISMISS_ERROR = 'SELECT_PHOTOS_DISMISS_ERROR';
export const SUBMIT_TASK_BEGIN = 'SUBMIT_TASK_BEGIN';
export const SUBMIT_TASK_SUCCESS = 'SUBMIT_TASK_SUCCESS';
export const SUBMIT_TASK_FAILURE = 'SUBMIT_TASK_FAILURE';
export const SUBMIT_TASK_DISMISS_ERROR = 'SUBMIT_TASK_DISMISS_ERROR';
export const REMOVE_SELECTED_PHOTO = 'REMOVE_SELECTED_PHOTO';
export const FETCH_USER_TASK_DATA_BEGIN = 'FETCH_USER_TASK_DATA_BEGIN';
export const FETCH_USER_TASK_DATA_SUCCESS = 'FETCH_USER_TASK_DATA_SUCCESS';
export const FETCH_USER_TASK_DATA_FAILURE = 'FETCH_USER_TASK_DATA_FAILURE';
export const FETCH_USER_TASK_DATA_DISMISS_ERROR =
  'FETCH_USER_TASK_DATA_DISMISS_ERROR';
export const PIN_TASK_BEGIN = 'PIN_TASK_BEGIN';
export const PIN_TASK_SUCCESS = 'PIN_TASK_SUCCESS';
export const PIN_TASK_FAILURE = 'PIN_TASK_FAILURE';
export const PIN_TASK_DISMISS_ERROR = 'PIN_TASK_DISMISS_ERROR';
export const SET_TEXT_INPUT = 'SET_TEXT_INPUT';
