export const CHECK_USER_EXISTENCE_BEGIN = 'CHECK_USER_EXISTENCE_BEGIN';
export const CHECK_USER_EXISTENCE_SUCCESS = 'CHECK_USER_EXISTENCE_SUCCESS';
export const CHECK_USER_EXISTENCE_FAILURE = 'CHECK_USER_EXISTENCE_FAILURE';
export const CHECK_USER_EXISTENCE_DISMISS_ERROR =
  'CHECK_USER_EXISTENCE_DISMISS_ERROR';
export const CREATE_NEW_CA_BEGIN = 'CREATE_NEW_CA_BEGIN';
export const CREATE_NEW_CA_SUCCESS = 'CREATE_NEW_CA_SUCCESS';
export const CREATE_NEW_CA_FAILURE = 'CREATE_NEW_CA_FAILURE';
export const CREATE_NEW_CA_DISMISS_ERROR = 'CREATE_NEW_CA_DISMISS_ERROR';
export const FETCH_TASK_LIST_BEGIN = 'FETCH_TASK_LIST_BEGIN';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAILURE = 'FETCH_TASK_LIST_FAILURE';
export const FETCH_TASK_LIST_DISMISS_ERROR = 'FETCH_TASK_LIST_DISMISS_ERROR';
