export default {
  appDev: [
    {
      id: '0',
      name: 'Shivam Chaudhary',
      position: '',
      phone: '',
      email: 'shivamchaudhary@iitgn.ac.in',
      src: require('../assets/Bitmojis/AppDev/Shivam.png'),
    },
    {
      id: '1',
      name: 'Xhitij Choudhary',
      position: '',
      phone: '',
      email: 'xhitij.cm@iitgn.ac.in',
      src: require('../assets/Bitmojis/AppDev/Xhitij.png'),
    },
    {
      id: '2',
      name: 'Varun Chandwani',
      position: '',
      phone: '',
      email: 'varun.chandwani@iitgn.ac.in',
      src: require('../assets/Bitmojis/AppDev/Varun.png'),
    },
    {
      id: '3',
      name: 'Mahesh Abhale',
      position: '',
      phone: '',
      email: 'abhale.mahesh@iitgn.ac.in',
      src: require('../assets/Bitmojis/AppDev/Mahesh.png'),
    },
  ],
  events: [
    {
      id: '0',
      name: 'Saagar Parikh',
      position: 'Core',
      phone: '+91 9712549922',
      email: 'saagar.p@iitgn.ac.in',
      src: require('../assets/Bitmojis/Events/Saagar.png'),
    },
    {
      id: '1',
      name: 'Aditi Agarwal',
      position: 'Coordinator',
      phone: '+91 7014153288',
      email: 'agarwal.aditi@iitgn.ac.in',
      src: require('../assets/Bitmojis/Events/Aditi.png'),
    },
    {
      id: '2',
      name: 'Harshvardhan Vala',
      position: 'Coordinator',
      phone: '+91 8140317228',
      email: 'harshvardhan.vala@iitgn.ac.in',
      src: require('../assets/Bitmojis/Events/Harshvardhan.png'),
    },
  ],
  sponsorship: [
    {
      id: '0',
      name: 'Progyan Das',
      position: 'Core',
      phone: '+91 6009884968',
      email: 'progyan.das@iitgn.ac.in',
      src: require('../assets/Bitmojis/Sponsorship/Progyan.png'),
    },
    {
      id: '1',
      name: 'Riya Bansal',
      position: 'Coordinator',
      phone: '+91 7249785909',
      email: 'riya.bansal@iitgn.ac.in',
      src: require('../assets/Bitmojis/Sponsorship/Riya.png'),
    },
  ],
  marketing: [
    {
      id: '0',
      name: 'Saniya Patwardhan',
      position: 'Core',
      phone: '+91 9850042104',
      email: 'patwardhan.saniya@iitgn.ac.in',
      src: require('../assets/Bitmojis/Marketing/Saniya.png'),
    },
    {
      id: '1',
      name: 'Hiral Sharma',
      position: 'Coordinator',
      phone: '+91 7977172936',
      email: 'hiral.s@iitgn.ac.in',
      src: require('../assets/Bitmojis/Marketing/Hiral.png'),
    },
    {
      id: '2',
      name: 'Haikoo Khandor',
      position: 'Coordinator',
      phone: '+91 9265275137',
      email: 'haikoo.ashok@iitgn.ac.in',
      src: require('../assets/Bitmojis/Marketing/Haikoo.png'),
    },
  ],
  design: [
    {
      id: '0',
      name: 'Shrija Agrawal',
      position: 'Core',
      phone: '+91 9428670002',
      email: 'shrija.agrawal@iitgn.ac.in',
      src: require('../assets/Bitmojis/Design/Shrija.png'),
    },
    {
      id: '1',
      name: 'Pavidhar Jain',
      position: 'Coordinator',
      phone: '+91 9610366556',
      email: 'pavidhar.jain@iitgn.ac.in',
      src: require('../assets/Bitmojis/Design/Pavidhar2.png'),
    },
    {
      id: '2',
      name: 'Sukruta Midigeshi',
      position: '+91 8310843531',
      phone: 'Coordinator',
      email: 'sukruta.midigeshi@iitgn.ac.in',
      src: require('../assets/Bitmojis/Design/Sukruta.png'),
    },
  ],
  cores: [
    {
      id: '0',
      name: 'Saagar Parikh',
      phone: '+91 9712549922',
      email: 'saagar.p@iitgn.ac.in',
      department: 'Events',
      src: require('../assets/Bitmojis/Events/Saagar.png'),
    },
    {
      id: '1',
      name: 'Progyan Das',
      phone: '+91 6009884968',
      email: 'progyan.das@iitgn.ac.in',
      department: 'Sponsorship',
      src: require('../assets/Bitmojis/Sponsorship/Progyan.png'),
    },
    {
      id: '2',
      name: 'Saniya Patwardhan',
      department: 'Marketing',
      phone: '+91 9850042104',
      email: 'patwardhan.saniya@iitgn.ac.in',
      src: require('../assets/Bitmojis/Marketing/Saniya.png'),
    },
    {
      id: '3',
      name: 'Shrija Agrawal',
      department: 'Design',
      phone: '+91 9428670002',
      email: 'shrija.agrawal@iitgn.ac.in',
      src: require('../assets/Bitmojis/Design/Shrija.png'),
    },
  ],
};
