export default PAST_EVENTS = [
    {id: 0, name: "Mezkala", description: "Groove in your blood and dance fury in your legs. Or in general, like to headbang to songs? Let us introduce you to Mezkala - a fusion dance competition.", rulebookSrc: "https://drive.google.com/file/d/1URoEm-x7YtOjVzlZPGql0OwFyQt7lVvm/view", image: require("../assets/pastEventBanners/event10_Mezkala.jpg")},

    {id: 1, name: "Reverb", description: "Blithchron is conducting a one-of-its-kind event, Reverb, which is an online EDM production. This event aims to give amateurs and professionals a chance to showcase their skills and bring out the best in them. EDM production competitions are rare, and we would love to unearth new talents and provide them with a platform.", rulebookSrc: "http://google.com", image: require("../assets/pastEventBanners/event9_Reverb.jpg")},

    {id: 2, name: "Unkahi", description: "Poetry mesmerizes the brain like no other form of literature can. It can take you on a journey or back in time, around the world in just a few characters or lines. We present to all the writers and observers or people in general, Unkahi - a Slam Poetry Competition. Participants have to compose their own poems and recite them on camera.", rulebookSrc: "https://drive.google.com/file/d/15wDl0I0TJWHb9NjuxD1pg7JhUgSAvhuV/view", image: require("../assets/pastEventBanners/event6_Unkahi.jpg")},

    {id: 3, name: "Quizzitch", description: "Test your knowledge about F.R.I.E.N.D.S and Harry Potter in the Best Fandom Quiz around succeeding the previous Quizzitch! We call all, be it millennials or GenZs, muggles or muggles(sad reality :'( ) to come together and take home the trophy-winning all the three rounds. You think you have the guts to call yourself 'The Chosen One?' You think you have what it takes to call yourselves true fans? We invite you and your friends to Quizzitch, a quiz like never before at Blithchron", rulebookSrc: "https://drive.google.com/file/d/1bZltddWs3XomZLjHp5WBHRViuUCGGfoK/view", image: require("../assets/pastEventBanners/event8_Quizzitch.jpg")},

    {id: 4, name: "Lenz Law", description: "To all the shutterbugs out there, here is your chance to capture the best you can! Presenting to you, Lenz Law! Lenz law is a photography event that intends to give budding and amateur photographers a chance to display their skills and creativity in various innovative sub-events. The sub-events are diverse and will provide something of interest for all kinds of photographers, beginners or experts. Judged by some of the most prominent people in the field, the event assures promising rewards for all the winners. So, get your lenses and gear up!",  rulebookSrc: "https://drive.google.com/file/d/1Lp6QRPN2vnEmKny2pgPWHPNpKjpDsS1z/view", image: require("../assets/pastEventBanners/event7_Lenz_Law.jpg")},

    {id: 5, name: "Rahasya", description: "Rahasya is an online treasure hunt event which is unique in its own way. When all other fests were finding the way to carry on, Blithchron came up with Rahasya where participants from all over the country enjoyed the event.", rulebookSrc: "http://google.com", image: require("../assets/pastEventBanners/event11_Rahasya.jpg")},
    
    {id: 6, name: "Zoetropy", description: "Zoetropy is a stop motion video making competition where participants can show off their storytelling, photography, animation, and sound editing skills. The theme for this year is 'Getting Creative with Food'.",  rulebookSrc: "http://google.com", image: require("../assets/pastEventBanners/event1_Zoetropy.jpg")},

    {id: 7, name: "Aesthescape", description: "Aesthescape is an art-making competition, a collaboration between Palette and Blithchron. This event tests artistic skills, creativity and spontaneity accordingly, and is the perfect platform for budding artists to showcase their talents both from inside the community and outside of it.", rulebookSrc: "http://google.com", image: require("../assets/pastEventBanners/event2_Aesthescape.jpg")},

    {id: 8, name: "Lips Don't Lie", description: "It is Blithchron's first dubbing competition. Dubbing here is essentially bad-lip reading of people in sports or characters in movies. Participants are expected to make a humourous interpretation of any video of their choice.", rulebookSrc: "http://google.com", image: require("../assets/pastEventBanners/event4_Lips_Dont_Lie.jpg")},
]