import {StyleSheet} from 'react-native';
import Colors from '../../../../utilities/Colors';
// import DimensionScale from '../../../../utilities/DimensionScale';

let style = {
  root: {flex: 1, backgroundColor: Colors.primaryDark},
  CATitleView: {paddingTop: 20, paddingLeft: 20},
  CATitleText: {fontSize: 45, fontWeight: 'bold'},
  pointsMainView: {
    backgroundColor: Colors.primaryDark,
    elevation: 10,
    height: 100,
    width: '88%',
    marginLeft: 20,
    marginTop: 20,
    borderRadius: 20,
    flexDirection: 'column',
    marginBottom: 50,
  },
  pointsBorderBox: {
    height: '80%',
    width: '90%',
    alignSelf: 'center',
    marginBottom: 'auto',
    marginTop: 'auto',
    borderRadius: 20,
    borderColor: Colors.borderPurple,
    borderWidth: 5,
    flexDirection: 'row',
  },
  pointsEarned: {
    borderRightColor: Colors.borderPurple,
    borderRightWidth: 5,
    flex: 1,
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  pinnedPoints: {
    borderRightColor: Colors.borderPurple,
    borderRightWidth: 5,
    flex: 1,
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  availablePoints: {
    flex: 1,
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  MainTasksView: {
    height: 620,
    width: '100%',
    marginTop: 0,
    marginLeft: 20,
    width: '88%',
    flexDirection: 'column',
  },
  tasksTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appDownloadPart: {
    backgroundColor: Colors.primaryDark,
    height: 150,
    width: '90%',
    alignSelf: 'center',
    marginTop: 20,
    borderRadius: 30,
    elevation: 3,
    flexDirection: 'row',
  },
  white10: {color: 'white', fontSize: 10},
  tasksTitleStyle: {color: 'white', fontWeight: 'bold', fontSize: 30},
  buttonTitleStyle: {fontSize: 10, color: 'white'},
  finishedTasksButton: {
    borderWidth: 3,
    borderRadius: 40,
    height: 40,
    width: 100,
    fontSize: 2,
    borderColor: 'green',
    marginRight: 10,
  },
  pinnedTasksButton: {
    borderWidth: 3,
    borderRadius: 40,
    height: 40,
    width: 90,
    fontSize: 2,
  },
  appDownloadsFirstColumn: {
    flex: 3,
    backgroundColor: Colors.primarySolid,
    height: '100%',
    flexDirection: 'column',
    paddingLeft: '5%',
    justifyContent: 'space-evenly',
    borderRadius: 30,
    paddingRight: '3%',
  },
  white15: {color: 'white', fontSize: 15},
  white8: {color: 'white', fontSize: 8},
  startEndDateStyle: {flexDirection: 'row', justifyContent: 'space-between'},
  pinIconStyle: {alignSelf: 'center', color: 'white'},
  pointsBox: {flex: 2, justifyContent: 'center', paddingHorizontal: '3%'},
  pointsBoxSquare: {
    borderWidth: 2,
    borderColor: Colors.borderPurple,
    height: '50%',
    flexDirection: 'column',
  },
  pointsBoxRow: {flex: 1, flexDirection: 'row'},
  pointsBoxTopLeft: {
    flex: 1,
    borderRightWidth: 2,
    borderRightColor: Colors.borderPurple,
    borderBottomColor: Colors.borderPurple,
    borderBottomWidth: 2,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  white6Center: {fontSize: 6, textAlign: 'center', color: 'white'},
  pointsBoxTopRight: {
    flex: 1,
    borderBottomWidth: 2,
    borderBottomColor: Colors.borderPurple,
    borderBottomWidth: 2,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  pointsBoxBottomLeft: {
    flex: 1,
    borderRightWidth: 2,
    borderRightColor: Colors.borderPurple,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  playButtonColumn: {flex: 1, justifyContent: 'center'},
  selfAlignCenter: {alignSelf: 'center'},
  pointsBoxBottomRight: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  rowFlex: {flexDirection: 'row'},
  leaderboardCard: {
    backgroundColor: Colors.primarySolid,
    height: 100,
    width: '100%',
    alignSelf: 'center',
    marginTop: 30,
    borderRadius: 15,
    elevation: 5,
    flexDirection: 'row',
  },
  profilePicLeaderboard: {
    flex: 1,
    height: '100%',
    flexDirection: 'column',
    paddingLeft: '5%',
    justifyContent: 'center',
    borderRadius: 30,
    paddingRight: '3%',
    alignItems: 'center',
  },
  nameAndCollege: {
    flex: 3,
    justifyContent: 'center',
    flexDirection: 'column',
    paddingLeft: 7,
  },
  white20: {color: 'white', fontSize: 20},
  white25: {color: 'white', fontSize: 25},
  white18: {color: 'white', fontSize: 18},
  pointsAndRank: {
    flex: 2,
    justifyContent: 'space-evenly',
    flexDirection: 'column',
    alignItems: 'center',
  },
  sixtyBySixty: {height: 60, width: 60},
};

export default StyleSheet.create(style);
